### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by AMDyes** [Waikkii/JD_Get_Cookie#1]
![image](https://user-images.githubusercontent.com/42004642/133986144-ca759518-daba-4796-957c-01523227870e.png)
这个是什么问题

**Comment by Waikkii** [comment]
> ![image](https://user-images.githubusercontent.com/42004642/133986144-ca759518-daba-4796-957c-01523227870e.png)
> 这个是什么问题

某些原因导致chromedriver下载失败，手动下载吧
下载链接：http://npm.taobao.org/mirrors/chromedriver
找到和Chrome同版本的chromedriver.exe放到main.exe同一级目录
