### ISSUE TITLE
软件打开后，cmd窗口闪退

### ISSUE THREAD

**Issue by wz36125** [Waikkii/JD_Get_Cookie#2]
如题

**Comment by Waikkii** [comment]
> 如题

手动下载chromedriver到文件目录试试

**Comment by thriken** [comment]
需要哪个版本啊   下载了90+  提示不兼容

**Comment by mackyuqimack** [comment]
我根据博主的源码，稍微调整后重新打了一个包，在win10上亲测可用
https://yuqi026.lanzouj.com/id45Dzyfgkf

**Comment by YuchuZhang** [comment]
需要安装chrome; 不能用其他浏览器

**Comment by 931122** [comment]
> 

你好，请问下如何编译的

**Comment by Waikkii** [comment]
> > 
> 
> 你好，请问下如何编译的

pyinstaller

**Comment by Waikkii** [comment]
> 如题

已更新
