### ISSUE TITLE
软件打开后 闪退

### ISSUE THREAD

**Issue by mythier** [Waikkii/JD_Get_Cookie#3]
软件打开后 chromedriver可以正常下载 也是相应的版本号 但没打开京东的网页 不知道是什么原因 也就是弹不出登录的窗口

**Comment by Waikkii** [comment]
> 软件打开后 chromedriver可以正常下载 也是相应的版本号 但没打开京东的网页 不知道是什么原因 也就是弹不出登录的窗口

已更新
