### ISSUE TITLE
无法自动下载对应的chromedriver版本

### ISSUE THREAD

**Issue by z960112559** [Waikkii/JD_Get_Cookie#5]
无法自动下载对应的chromedriver版本，目前看是因为 http://npm.taobao.org/mirrors/chromedriver/ 返回数据变了，好像改成js生成dom了

**Comment by mackyuqimack** [comment]
https://yuqi026.lanzouj.com/id45Dzyfgkf

**Comment by Waikkii** [comment]
> 无法自动下载对应的chromedriver版本，目前看是因为 http://npm.taobao.org/mirrors/chromedriver/ 返回数据变了，好像改成js生成dom了

已更新
