### ISSUE TITLE
打开就闪退

### ISSUE THREAD

**Issue by jsdfhasuh** [Waikkii/JD_Get_Cookie#7]

**Comment by jsdfhasuh** [comment]
![image](https://user-images.githubusercontent.com/49879362/153734996-79563783-970d-49e3-82ba-10e1cb39f540.png)

**Comment by MichaelthA** [comment]
我也遇到了

**Comment by 365360171** [comment]
我安装python运行，提示要chrome

**Comment by ChellyL** [comment]
下载最新版 https://github.com/Waikkii/JD_Get_Cookie/releases/tag/V2.0

**Comment by luyan29** [comment]
> 

最新版命令行结束，未启动登陆网页

**Comment by QiuYuCode** [comment]
> > 
> 
> 最新版命令行结束，未启动登陆网页

去 ChromeDriver 官网找到并下载与本机 Chrome 对应版本的 Driver ，放到与主程序同级目录下就好了~
> https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by kingszhe9664** [comment]
![360截图20220312213005556](https://user-images.githubusercontent.com/35531941/158019859-90c4641d-62ff-43f4-a79f-b728be9eaebd.jpg)
 这个怎么解决啊
